/*RELLENO LAS TABLAS AUXILIARES*/

USE ODS;

INSERT INTO ODS_DM_CANALES VALUES (1, 'ONLINE', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (2, 'CALLCENTER', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (3, 'RETAIL', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (4, 'APP', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_CANALES VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

INSERT INTO ODS_DM_PRODUCTOS VALUES (1, 'TIME-OF-USE', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (2, 'TIERED RATE', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (3, 'ELECTRIC VEHICLE BASE', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (4, 'NET ENERGY METERING ADD-ON', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (5, 'SOLAR CHOICE', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (6, 'SMARTRATE', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_PRODUCTOS VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;
