/* TABLAS TEMPORALES DIRECCIONES SERVICIOS*/


USE ODS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS;
CREATE TABLE TMP_DIRECCIONES_SERVICIOS AS
SELECT 
CASE WHEN LENGTH(TRIM(PRO.PRODUCT_ADDRESS))<>0 THEN UPPER(TRIM(PRO.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END DE_DIRECCION
, CASE WHEN LENGTH(TRIM(PRO.PRODUCT_POSTAL_CODE))<>0 THEN TRIM(PRO.PRODUCT_POSTAL_CODE) ELSE 99999 END DE_CP
, CASE WHEN LENGTH(TRIM(PRO.PRODUCT_CITY))<>0 THEN TRIM(UPPER(PRO.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END DE_CIUDAD
, CASE WHEN LENGTH(TRIM(PRO.PRODUCT_STATE))<>0 THEN TRIM(UPPER(PRO.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END DE_ESTADO
, CASE WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN UPPER(TRIM(REPLACE(PRO.PRODUCT_COUNTRY,'United States','US'))) ELSE 'DESCONOCIDO' END DE_PAIS
FROM STAGE.STG_PRODUCTOS_CRM PRO;

ANALYZE TABLE TMP_DIRECCIONES_SERVICIOS;

USE ODS;
DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS2;
CREATE TABLE TMP_DIRECCIONES_SERVICIOS2 AS
SELECT DISTINCT PRO.PRODUCT_ID ID_SERVICIO
, DIR.DE_DIRECCION DE_DIRECCION
, DIR.DE_CP DE_CP
, DIR.DE_CIUDAD DE_CIUDAD
, DIR.DE_ESTADO DE_ESTADO
, DIR.DE_PAIS DE_PAIS
FROM STAGE.STG_PRODUCTOS_CRM PRO
INNER JOIN ODS.TMP_DIRECCIONES_SERVICIOS DIR ON CASE WHEN LENGTH(TRIM(PRO.PRODUCT_ADDRESS))<>0 THEN UPPER(TRIM(PRO.PRODUCT_ADDRESS)) ELSE 'DESCONOCIDO' END=DIR.DE_DIRECCION
											AND CASE WHEN LENGTH(TRIM(PRO.PRODUCT_POSTAL_CODE))<>0 THEN TRIM(PRO.PRODUCT_POSTAL_CODE) ELSE 99999 END=DIR.DE_CP
                                            AND CASE WHEN LENGTH(TRIM(PRO.PRODUCT_CITY))<>0 THEN UPPER(TRIM(PRO.PRODUCT_CITY)) ELSE 'DESCONOCIDO' END=DIR.DE_CIUDAD
											AND CASE WHEN LENGTH(TRIM(PRO.PRODUCT_STATE))<>0 THEN UPPER(TRIM(PRO.PRODUCT_STATE)) ELSE 'DESCONOCIDO' END=DIR.DE_ESTADO
                                            AND CASE WHEN LENGTH(TRIM(PRO.PRODUCT_COUNTRY))<>0 THEN UPPER(TRIM(REPLACE(PRO.PRODUCT_COUNTRY,'United States','US'))) ELSE 'DESCONOCIDO' END=DIR.DE_PAIS
;

ANALYZE TABLE TMP_DIRECCIONES_SERVICIOS2;

