/*COMPARATIVA CON DIRECCIONES YA EXISTENTES

PRIMERO SE LE METE ID CIUDAD
*/
USE ODS;

DROP TABLE IF EXISTS TMP_DIRECCIONES_SERVICIOS3;
CREATE TABLE TMP_DIRECCIONES_SERVICIOS3 AS
SELECT
DE_DIRECCION DE_DIRECCION
,DE_CP DE_CP
,CASE WHEN LENGTH(TRIM(CIU.ID_CIUDAD_ESTADO))<>0 THEN TRIM(CIU.ID_CIUDAD_ESTADO) ELSE '999' END ID_CIUDAD_ESTADO
FROM TMP_DIRECCIONES_SERVICIOS2 DIR
LEFT OUTER JOIN ODS_DM_CIUDADES_ESTADOS CIU ON CIU.DE_CIUDAD = DIR.DE_CIUDAD
AND CIU.DE_ESTADO = DIR.DE_ESTADO;


/*A CONTINUACION LA COMPARATIVA*/

SELECT DISTINCT TMP.DE_DIRECCION DE_DIRECCION, TMP.DE_CP, TMP.ID_CIUDAD_ESTADO
FROM TMP_DIRECCIONES_SERVICIOS3 TMP
LEFT OUTER JOIN ODS_HC_DIRECCIONES DIR ON
(DIR.DE_DIRECCION = TMP.DE_DIRECCION
AND DIR.DE_CP = TMP.DE_CP
AND DIR.ID_CIUDAD_ESTADO = TMP.ID_CIUDAD_ESTADO)
WHERE DIR.ID_DIRECCION IS NULL
;

/*INSERT EN HC_DIRECCIONES PARA OBTENER ID_DIRECCION DE LAS NUEVAS*/
USE ODS;
INSERT INTO ODS.ODS_HC_DIRECCIONES
(DE_DIRECCION, DE_CP, ID_CIUDAD_ESTADO, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT TMP.DE_DIRECCION DE_DIRECCION, TMP.DE_CP, TMP.ID_CIUDAD_ESTADO, NOW(), NOW()
FROM TMP_DIRECCIONES_SERVICIOS3 TMP
LEFT OUTER JOIN ODS_HC_DIRECCIONES DIR ON
(DIR.DE_DIRECCION = TMP.DE_DIRECCION
AND DIR.DE_CP = TMP.DE_CP
AND DIR.ID_CIUDAD_ESTADO = TMP.ID_CIUDAD_ESTADO)
WHERE DIR.ID_DIRECCION IS NULL
;

COMMIT;