/* CREAMOS LOS FK PARA RELACIONAR LAS TABLAS DE SERVICIOS */

USE ODS;

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_canal_idx (ID_CANAL ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_canal FOREIGN KEY (ID_CANAL)
REFERENCES ODS.ODS_DM_CANALES (ID_CANAL);

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_prod_idx (ID_PRODUCTO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_prod FOREIGN KEY (ID_PRODUCTO)
REFERENCES ODS.ODS_DM_PRODUCTOS (ID_PRODUCTO);

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_cli_idx (ID_CLIENTE ASC);

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_cli FOREIGN KEY (ID_CLIENTE)
REFERENCES ODS.ODS_HC_CLIENTES (ID_CLIENTE);

ALTER TABLE ODS.ODS_HC_SERVICIOS MODIFY COLUMN ID_DIRECCION_SERVICIO INT(10) UNSIGNED;

ALTER TABLE ODS.ODS_HC_SERVICIOS ADD INDEX fk_serv_dir_idx (ID_DIRECCION_SERVICIO ASC);
ALTER TABLE ODS.ODS_HC_SERVICIOS ADD CONSTRAINT fk_serv_dir FOREIGN KEY (ID_DIRECCION_SERVICIO)
REFERENCES ODS.ODS_HC_DIRECCIONES (ID_DIRECCION);







