/*CREO TABLAS DE FACTURAS EN ODS*/

USE ODS;

DROP TABLE IF EXISTS ODS_HC_FACTURAS;
CREATE TABLE IF NOT EXISTS ODS_HC_FACTURAS
(ID_FACTURA INT UNSIGNED NOT NULL PRIMARY KEY
, ID_CLIENTE INT
, FC_INICIO DATETIME
, FC_FIN DATETIME
, FC_ESTADO DATETIME
, FC_PAGO DATETIME
, ID_CICLO_FACTURACION INT 
, ID_METODO_PAGO INT 
, CANTIDAD FLOAT
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);
ANALYZE TABLE ODS_HC_FACTURAS;

DROP TABLE IF EXISTS ODS_DM_METODOS_PAGO;
CREATE TABLE IF NOT EXISTS ODS_DM_METODOS_PAGO
(ID_METODO_PAGO INT NOT NULL PRIMARY KEY
, DE_METODO_PAGO VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);
ANALYZE TABLE ODS_DM_METODOS_PAGO;

DROP TABLE IF EXISTS ODS_DM_CICLOS_FACTURACION;
CREATE TABLE IF NOT EXISTS ODS_DM_CICLOS_FACTURACION
(ID_CICLO_FACTURACION INT NOT NULL PRIMARY KEY
, DE_CICLO_FACTURACION VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);
ANALYZE TABLE ODS_DM_CICLOS_FACTURACION;


