/*RELLENO LAS TABLAS FACTURAS*/

USE ODS;

INSERT INTO ODS_DM_CICLOS_FACTURACION VALUES (1, 'M01', NOW(), NOW());
INSERT INTO ODS_DM_CICLOS_FACTURACION VALUES (2, 'M15', NOW(), NOW());
INSERT INTO ODS_DM_CICLOS_FACTURACION VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_CICLOS_FACTURACION VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

USE ODS;

INSERT INTO ODS_DM_METODOS_PAGO VALUES (1, 'DIRECT DEBIT', NOW(), NOW());
INSERT INTO ODS_DM_METODOS_PAGO VALUES (2, 'CREDIT CARD', NOW(), NOW());
INSERT INTO ODS_DM_METODOS_PAGO VALUES (3, 'CHECK PAYMENT', NOW(), NOW());
INSERT INTO ODS_DM_METODOS_PAGO VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_METODOS_PAGO VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;
