/* COMPROBAMOS QUE LOS TELEFONOS DEL IVR NO SE CORRESPONDEN CON LOS TELEFONOS DE LA TABLA DE CLIENTE

SELECT * FROM STAGE.STG_CONTACTOS_IVR A
INNER JOIN ODS.ODS_HC_CLIENTES B
ON A.PHONE_NUMBER = B.TELEFONO_CLIENTE;

Y AÑADIMOS A LA TABLA DE CLIENTES UN REGISTRO DESCONOCIDO PARA PODER HACER LA FOREIGN KEY QUE RELACIONE AMBAS TABLAS*/

USE ODS;

INSERT INTO ODS_HC_CLIENTES VALUES (
99999
, 'DESCONOCIDO'
, 'DESCONOCIDO'
, '99-999-9999'
, 99
, 999999
, 9999999999
, 'DESCONOCIDO'
, STR_TO_DATE('9999-12-31','%Y-%m-%d')
, 999
, 999
, NOW()
, STR_TO_DATE('9999-12-31 00:00:00','%Y-%m-%d %H:%i:%s'));

COMMIT;