/*RELLENO LAS TABLAS DE DIMENSIONES DE LLAMADAS*/

USE ODS;

INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (1, 'COLLECTIONS', NOW(), NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (2, 'CUSTOMER SERVICE', NOW(), NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (3, 'SALES', NOW(), NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (4, 'CLAIMS', NOW(), NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (5, 'SUPPORT', NOW(), NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (6, 'FINANCIALS', NOW(), NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_DEPARTAMENTOS_CC VALUES (98, 'NO APLICA', NOW(), NOW());

COMMIT;

INSERT INTO ODS_DM_AGENTES_CC (DE_AGENTE_CC, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(AGENT)) DE_AGENTE_CC, NOW(), NOW()
FROM STAGE.STG_CONTACTOS_IVR
WHERE LENGTH(TRIM(AGENT))<>0;

COMMIT;

INSERT INTO ODS_DM_AGENTES_CC VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_AGENTES_CC VALUES (998, 'NO APLICA', NOW(), NOW());

COMMIT;
