/*RELLENAMOS LA TABLA PRINCIPAL: LLAMADAS*/

USE ODS;

INSERT INTO ODS_HC_LLAMADAS (ID_IVR, TELEFONO_LLAMADA, ID_CLIENTE, FC_INICIO_LLAMADA, FC_FIN_LLAMADA, ID_DEPARTAMENTO_CC, FLG_TRANSFERIDO, ID_AGENTE_CC, FC_INSERT, FC_MODIFICACION)
SELECT ID ID_IVR
, CASE WHEN LENGTH(TRIM(PHONE_NUMBER))<>0 THEN TRIM(PHONE_NUMBER) ELSE 9999999999 END TELEFONO_LLAMADA
, 99999
, CASE WHEN LENGTH(TRIM(START_DATETIME))<>0 THEN TRIM(START_DATETIME) ELSE STR_TO_DATE('31/12/9999 23:59:59','%d/%m/%Y %H:%i:%s') END FC_INICIO_LLAMADA
, CASE WHEN LENGTH(TRIM(END_DATETIME))<>0 THEN TRIM(END_DATETIME) ELSE STR_TO_DATE('31/12/9999 23:59:59','%d/%m/%Y %H:%i:%s') END FC_FIN_LLAMADA
, DEP.ID_DEPARTAMENTO_CC
, CASE WHEN TRIM(UPPER(FLG_TRANSFER))='TRUE' THEN 1 ELSE 0 END FLG_TRANSFERIDO
, AGENTE.ID_AGENTE_CC
, NOW()
, STR_TO_DATE('31/12/9999','%d/%m/%Y')
FROM STAGE.STG_CONTACTOS_IVR LLAMADAS
INNER JOIN ODS.ODS_DM_AGENTES_CC AGENTE ON CASE WHEN LENGTH(TRIM(LLAMADAS.AGENT))<>0 THEN UPPER(TRIM(LLAMADAS.AGENT)) ELSE 'DESCONOCIDO' END=AGENTE.DE_AGENTE_CC
INNER JOIN ODS.ODS_DM_DEPARTAMENTOS_CC DEP ON CASE WHEN LENGTH(TRIM(LLAMADAS.SERVICE))<>0 THEN UPPER((TRIM(LLAMADAS.SERVICE))) ELSE 'DESCONOCIDO' END=DEP.DE_DEPARTAMENTO_CC

;

COMMIT;

ANALYZE TABLE ODS_HC_LLAMADAS;
