/* COMPROBAMOS QUE TODAS LAS ID SERVICIOS DE LA TABLA DE ORDERS ESTAN EN LA TABLA DE SERVICIOS*/

SELECT * FROM STAGE.STG_ORDERS_CRM A
LEFT OUTER JOIN STAGE.STG_PRODUCTOS_CRM B
ON A.ORDER = B.PRODUCT_ID
WHERE B.PRODUCT_ID IS NULL;

/* EL RESULTADO SON 0 FILAS DEVUELTAS CON LO QUE QUEDA COMPROBADO */