/*CREO TABLAS DE PEDIDOS EN ODS*/

USE ODS;

DROP TABLE IF EXISTS ODS_HC_PEDIDOS;
CREATE TABLE IF NOT EXISTS ODS_HC_PEDIDOS
(ID_PEDIDO INT NOT NULL AUTO_INCREMENT PRIMARY KEY
, ID_ORD INT
, ID_SERVICIO INT UNSIGNED
, ID_FASE_ORD INT
, ID_AGENTE_ORD INT
, FC_INICIO_PEDIDO DATETIME
, FC_FIN_PEDIDO DATETIME
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);
ANALYZE TABLE ODS_HC_PEDIDOS;

DROP TABLE IF EXISTS ODS_DM_FASES_ORD;
CREATE TABLE IF NOT EXISTS ODS_DM_FASES_ORD
(ID_FASE_ORD INT NOT NULL PRIMARY KEY
, DE_FASE_ORD VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);
ANALYZE TABLE ODS_DM_FASES_ORD;

DROP TABLE IF EXISTS ODS_DM_AGENTES_ORD;
CREATE TABLE IF NOT EXISTS ODS_DM_AGENTES_ORD
(ID_AGENTE_ORD INT NOT NULL AUTO_INCREMENT PRIMARY KEY
, DE_AGENTE_ORD VARCHAR(512)
, FC_INSERT DATETIME
, FC_MODIFICACION DATETIME);
ANALYZE TABLE ODS_DM_AGENTES_ORD;
