/*RELLENO LAS TABLAS DE DIMENSIONES DE PEDIDOS*/

USE ODS;

INSERT INTO ODS_DM_FASES_ORD VALUES (1, 'INIT', NOW(), NOW());
INSERT INTO ODS_DM_FASES_ORD VALUES (2, 'NETWORK CONNECTION', NOW(), NOW());
INSERT INTO ODS_DM_FASES_ORD VALUES (3, 'PREPARING LOGISTIC', NOW(), NOW());
INSERT INTO ODS_DM_FASES_ORD VALUES (4, 'SHIPPED', NOW(), NOW());
INSERT INTO ODS_DM_FASES_ORD VALUES (5, 'DELIVERED', NOW(), NOW());
INSERT INTO ODS_DM_FASES_ORD VALUES (6, 'CANCEL', NOW(), NOW());
INSERT INTO ODS_DM_FASES_ORD VALUES (7, 'REFUND', NOW(), NOW());
INSERT INTO ODS_DM_FASES_ORD VALUES (99, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_FASES_ORD VALUES (98, 'NO APLICA', NOW(), NOW());
COMMIT;

INSERT INTO ODS_DM_AGENTES_ORD (DE_AGENTE_ORD, FC_INSERT, FC_MODIFICACION)
SELECT DISTINCT UPPER(TRIM(AGENT)) DE_AGENTE_ORD, NOW(), NOW()
FROM STAGE.STG_ORDERS_CRM
WHERE LENGTH(TRIM(AGENT))<>0;
COMMIT;

INSERT INTO ODS_DM_AGENTES_ORD VALUES (999, 'DESCONOCIDO', NOW(), NOW());
INSERT INTO ODS_DM_AGENTES_ORD VALUES (998, 'NO APLICA', NOW(), NOW());
COMMIT;


