/*RELLENAMOS LA TABLA PRINCIPAL: PEDIDOS*/

USE ODS;
INSERT INTO ODS_HC_PEDIDOS (ID_ORD, ID_SERVICIO, ID_FASE_ORD, ID_AGENTE_ORD, FC_INICIO_PEDIDO, 
FC_FIN_PEDIDO, FC_INSERT, FC_MODIFICACION)
SELECT ID ID_ORD
, TRIM(ORDERS.ORDER) ID_SERVICIO
, FASE.ID_FASE_ORD
, AGENTE.ID_AGENTE_ORD
, CASE WHEN LENGTH(TRIM(START_DT))<>0 THEN TRIM(START_DT) ELSE 
STR_TO_DATE('31/12/9999 23:59:59','%d/%m/%Y %H:%i:%s') END FC_INICIO_PEDIDO
, CASE WHEN LENGTH(TRIM(END_DT))<>0 THEN TRIM(END_DT) 
ELSE STR_TO_DATE('31/12/9999 23:59:59','%d/%m/%Y %H:%i:%s') END FC_FIN_PEDIDO
, NOW()
, STR_TO_DATE('31/12/9999','%d/%m/%Y')
FROM STAGE.STG_ORDERS_CRM ORDERS
INNER JOIN ODS.ODS_DM_AGENTES_ORD AGENTE ON CASE WHEN LENGTH(TRIM(ORDERS.AGENT))<>0 
THEN UPPER(TRIM(ORDERS.AGENT)) ELSE 'DESCONOCIDO' END=AGENTE.DE_AGENTE_ORD
INNER JOIN ODS.ODS_DM_FASES_ORD FASE ON CASE WHEN LENGTH(TRIM(ORDERS.PHASE))<>0 
THEN UPPER((TRIM(ORDERS.PHASE))) ELSE 'DESCONOCIDO' END=FASE.DE_FASE_ORD;
COMMIT;
ANALYZE TABLE ODS_HC_PEDIDOS;


