/* CREAMOS LOS FK PARA RELACIONAR LAS TABLAS DE PEDIDOS */

USE ODS;

ALTER TABLE ODS.ODS_HC_PEDIDOS ADD INDEX fk_ped_fase_idx (ID_FASE_ORD ASC);
ALTER TABLE ODS.ODS_HC_PEDIDOS ADD CONSTRAINT fk_ped_fase FOREIGN KEY (ID_FASE_ORD)
REFERENCES ODS.ODS_DM_FASES_ORD (ID_FASE_ORD);

ALTER TABLE ODS.ODS_HC_PEDIDOS ADD INDEX fk_ped_agent_idx (ID_AGENTE_ORD ASC);
ALTER TABLE ODS.ODS_HC_PEDIDOS ADD CONSTRAINT fk_ped_agent FOREIGN KEY (ID_AGENTE_ORD)
REFERENCES ODS.ODS_DM_AGENTES_ORD (ID_AGENTE_ORD);

ALTER TABLE ODS.ODS_HC_PEDIDOS ADD INDEX fk_ped_serv_idx (ID_SERVICIO ASC);
ALTER TABLE ODS.ODS_HC_PEDIDOS ADD CONSTRAINT fk_ped_serv FOREIGN KEY (ID_SERVICIO)
REFERENCES ODS.ODS_HC_SERVICIOS (ID_SERVICIO);