USE ODS;
SELECT TRIM(SUBSTRING(DE_DIRECCION, 1 , INSTR(DE_DIRECCION,' ')-1)) AS NUM_VIA
, TRIM(SUBSTRING(DE_DIRECCION, INSTR(DE_DIRECCION,' ')+1, LENGTH(DE_DIRECCION))) AS NOMBRE_VIA
FROM ODS.ODS_HC_DIRECCIONES;



