/*ANALIZAMOS LAS TABLAS PARA QUE FUNCIONE MEJOR */

USE ODS;

ANALYZE TABLE ODS_DM_PROFESIONES;
ANALYZE TABLE ODS_DM_SEXOS;
ANALYZE TABLE ODS_HC_DIRECCIONES;
ANALYZE TABLE ODS_DM_CIUDADES_ESTADOS;
ANALYZE TABLE ODS_DM_PAISES;
ANALYZE TABLE ODS_COMPANYAS;
ANALYZE TABLE ODS_HC_CLIENTES;
